modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="supercircuitmaker"
version="${file.jarVersion}"
displayName="Super Circuit Maker"
authors="amadornes"
description='''
Tiny Circuits Galore!
'''

[[dependencies.supercircuitmaker]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"
[[dependencies.supercircuitmaker]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.supercircuitmaker]]
modId="tklib"
mandatory=true
versionRange="[0.0.7,1.0.0)"
ordering="NONE"
side="BOTH"
